### ISSUE TITLE
Add code of finding power of 2 in O(1) time complexity in a new file

### ISSUE THREAD

**Issue by codea-holic** [codea-holic/Advance-data-structure-java#2]
**Write a code for power of 2 in O(1) time complexity in a new file .**

_Input:-_
`5`

_Output:-_ 
`32`

**Comment by alimustafashah** [comment]
It is not possible in O(1).

**Comment by alimustafashah** [comment]
A possible solution that comes to my mind is
`
double computePower(int n) {
     Boolean isNegative = false;
     if (n < 0) {
          n = -n;
          isNegative = true;
     }
     int temp = 1 << n;
     if (isNegative)
          return 1/(double)temp;
     else
          return temp;
}
`

Here the following line does the magic
`int temp = 1 << n;`
At first I thought that the above line maybe O(n) but then the counter that I gave to myself was that when we multiply two numbers based on the input e.g. n * n it is still O(1).

**Comment by syedmalimustafa** [comment]
A possible solution that comes to my mind is

```
double computePower(int n) {
    Boolean isNegative = false;
    if (n < 0) {
        n = -n;
        isNegative = true;
    } 
    int temp = 1 << n;
    if (isNegative)
        return 1/(double)temp;
    else
        return temp;
}
```

Here the following line does the magic
`int temp = 1 << n;`
At first I thought that the above line maybe O(n) but then the counter that I gave to myself was that when we multiply two numbers based on the input e.g. n * n it is still O(1).

**Comment by codea-holic** [comment]
Perfect,
Make a pull request make sure to add the file in the Bit-Manipulation directory.
